// lib/typst/custom-template-generator.ts
// Generates a custom Typst template from a CS's uploaded PDF analysis

export function generateCustomTypstTemplate(templateAnalysis: {
  custom_instructions?: string
  header_style?: string
  section_style?: string
  resolution_style?: string
  signature_style?: string
  font_notes?: string
  formatting_rules?: string[]
}): string {
  // Parse the analysis to determine styling choices
  const isSerifFont = !templateAnalysis.font_notes?.toLowerCase().includes('sans')
  const hasBoldSections = templateAnalysis.section_style?.toLowerCase().includes('bold')
  const hasNumberedSections = templateAnalysis.formatting_rules?.some(r =>
    r.toLowerCase().includes('number') || r.toLowerCase().includes('roman')
  )

  return `// Custom Typst template generated from CS's uploaded PDF format
// Generated by SecretaryOS template analyzer

#let doc(
  company_name: "Company Name",
  cin: "",
  meeting_date: "",
  generated_by: "SecretaryOS",
  body
) = {
  set page(
    paper: "a4",
    margin: (top: 2.8cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
    header: [
      #set text(size: 8pt, fill: rgb("#B8973A"))
      #grid(
        columns: (1fr, 1fr),
        [#set text(weight: "bold", tracking: 2pt); SECRETARYOS],
        align(right)[#set text(fill: rgb("#888888")); Companies Act 2013 Compliant]
      )
      #line(length: 100%, stroke: 0.5pt + rgb("#0A0F1E"))
    ],
    footer: context [
      #line(length: 100%, stroke: 0.5pt + rgb("#dddddd"))
      #v(3pt)
      #set text(size: 7.5pt, fill: rgb("#999999"))
      #grid(
        columns: (1fr, 1fr),
        [Generated by SecretaryOS · #company_name · #cin],
        align(right)[#meeting_date · Page #counter(page).display()]
      )
    ]
  )

  set text(
    font: (${isSerifFont ? '"Times New Roman", "Liberation Serif", "serif"' : '"Arial", "Helvetica", "sans-serif"'}),
    size: 11pt,
    lang: "en"
  )

  set par(justify: true, leading: 0.8em, spacing: 0.6em)

  body
}

#let doc-title(content) = {
  set align(center)
  set text(size: 14pt, weight: "bold")
  upper(content)
  v(4pt)
}

#let doc-center(content) = {
  set align(center)
  set text(size: 10pt)
  content
  v(2pt)
}

#let doc-divider() = {
  v(4pt)
  align(center, line(length: 50%, stroke: 0.5pt + rgb("#B8973A")))
  v(4pt)
}

#let doc-section(content) = {
  v(14pt)
  set text(
    size: 9pt,
    weight: ${hasBoldSections ? '"bold"' : '"regular"'},
    fill: rgb("#B8973A"),
    tracking: 1.5pt
  )
  upper(content)
  v(2pt)
  line(length: 100%, stroke: 0.5pt + rgb("#e0e0e0"))
  v(4pt)
}

#let doc-line(content) = {
  pad(left: 10pt)[
    #set text(size: 10.5pt)
    #content
  ]
  v(4pt)
}

#let doc-resolution(content) = {
  v(6pt)
  block(
    width: 100%,
    fill: rgb("#FAFAF8"),
    stroke: (left: 3pt + rgb("#B8973A")),
    inset: (left: 12pt, right: 12pt, top: 8pt, bottom: 8pt)
  )[
    #set text(size: 10.5pt)
    #content
  ]
  v(4pt)
}

#let doc-further(content) = {
  v(3pt)
  block(
    width: 100%,
    fill: rgb("#F8F8F6"),
    stroke: (left: 2pt + rgb("#cccccc")),
    inset: (left: 12pt, right: 12pt, top: 6pt, bottom: 6pt)
  )[
    #set text(size: 10.5pt)
    #content
  ]
  v(4pt)
}

#let doc-sig(
  chairman_name: "",
  chairman_din: "",
  cs_name: "",
  cs_membership: "",
  date: "",
  place: ""
) = {
  v(24pt)
  line(length: 100%, stroke: 0.5pt + rgb("#dddddd"))
  v(12pt)
  grid(
    columns: (1fr, 1fr),
    gutter: 20pt,
    [
      #set text(size: 9.5pt)
      *CHAIRMAN OF THE MEETING*
      #v(24pt)
      #line(length: 80%, stroke: 0.5pt + black)
      #v(3pt)
      Name: #chairman_name \\
      DIN: #chairman_din \\
      Date: #date \\
      Place: #place
    ],
    [
      #set text(size: 9.5pt)
      *COMPANY SECRETARY*
      #v(24pt)
      #line(length: 80%, stroke: 0.5pt + black)
      #v(3pt)
      Name: #cs_name \\
      Membership No.: #cs_membership \\
      Date: #date \\
      Place: #place
    ]
  )
}
`
}
