import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — SecretaryOS',
  description: 'SecretaryOS Terms of Service and Liability Disclaimer',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-app-bg">
      <div className="max-w-3xl mx-auto px-4 py-12 sm:py-16">

        {/* Header */}
        <div className="mb-10">
          <Link href="/" className="font-serif text-xl font-bold text-ink">
            Secretary<span className="text-teal">OS</span>
          </Link>
          <h1 className="mt-6 text-3xl font-bold text-ink">Terms of Service</h1>
          <p className="text-gray-500 text-sm mt-1">Last updated: April 2025 &nbsp;·&nbsp; Version 1.0</p>
        </div>

        {/* Notice box */}
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-10">
          <p className="text-amber-900 font-semibold text-sm">
            Important: SecretaryOS generates AI-powered draft documents for professional review. All documents are drafts only. You are solely responsible for reviewing, verifying, and filing them correctly.
          </p>
        </div>

        <div className="prose prose-sm prose-gray max-w-none space-y-8">

          <Section number="1" title="Service Description">
            <p>
              SecretaryOS is an AI-powered tool that assists Company Secretaries in generating draft compliance documents including Board Meeting Notices, Agendas, and Minutes. SecretaryOS does <strong>not</strong> provide legal advice, legal services, or act as your legal counsel.
            </p>
            <p>
              Documents generated are for use as a starting point for your own professional review and drafting. The output is produced by artificial intelligence and must be treated accordingly.
            </p>
          </Section>

          <Section number="2" title="Draft Documents Only">
            <p>
              All documents generated by SecretaryOS are <strong>DRAFTS ONLY</strong>. They are intended for professional review and must never be used, filed, or distributed without thorough verification by a qualified Company Secretary.
            </p>
            <p>
              AI-generated content may contain errors, omissions, outdated legal references, or incorrect formatting. You are responsible for identifying and correcting such issues before any use.
            </p>
          </Section>

          <Section number="3" title="User Responsibility">
            <p>By using SecretaryOS, you accept full and sole responsibility for:</p>
            <ul>
              <li>All content in documents generated using this platform</li>
              <li>The accuracy of information you provide as input</li>
              <li>Legal compliance of documents before filing</li>
              <li>Verification against applicable laws and regulations including the Companies Act, 2013</li>
              <li>Review by a qualified professional (yourself or a senior colleague) before any use</li>
              <li>Ensuring documents meet the standards required by ROC and other regulatory bodies</li>
              <li>Any consequences arising from errors, omissions, or non-compliance</li>
            </ul>
            <p>
              You acknowledge that you are a qualified professional and will apply your own judgment, knowledge, and expertise to every document generated.
            </p>
          </Section>

          <Section number="4" title="Liability Disclaimer">
            <p>
              SecretaryOS is provided <strong>"AS IS"</strong> without any warranties, express or implied, including but not limited to warranties of accuracy, completeness, fitness for a particular purpose, or non-infringement.
            </p>
            <p>SecretaryOS does <strong>NOT</strong>:</p>
            <ul>
              <li>Guarantee the accuracy of AI-generated content</li>
              <li>Provide legal advice or legal services</li>
              <li>Accept liability for errors, omissions, or consequences arising from use of generated documents</li>
              <li>Accept liability for filing errors, regulatory violations, or penalties</li>
              <li>Accept liability for any damage to your professional reputation or licence</li>
              <li>Accept liability for any financial loss, regulatory action, or legal proceedings</li>
            </ul>
          </Section>

          <Section number="5" title="Indemnification">
            <p>
              By using SecretaryOS, you agree to indemnify, defend, and hold harmless SecretaryOS, its owners, officers, employees, and agents from and against any and all claims, damages, losses, liabilities, costs, and expenses (including legal fees) arising from or related to:
            </p>
            <ul>
              <li>Your use of the platform and generated documents</li>
              <li>Any filing or submission made using documents generated on this platform</li>
              <li>Your violation of these Terms of Service</li>
              <li>Any inaccuracy in information you provided</li>
            </ul>
          </Section>

          <Section number="6" title="Usage Policy">
            <p>All users must:</p>
            <ul>
              <li>Review all documents before filing or any professional use</li>
              <li>Make all necessary corrections and amendments</li>
              <li>Sign off as the responsible professional</li>
              <li>Comply with all applicable laws and regulations</li>
              <li>Not file any document without proper verification</li>
              <li>Use the platform only for lawful purposes</li>
            </ul>
          </Section>

          <Section number="7" title="Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, SecretaryOS's total aggregate liability to you for all claims arising under or related to these Terms or the use of the service shall be limited to the fees you paid to SecretaryOS in the thirty (30) days immediately preceding the claim.
            </p>
            <p>
              In no event shall SecretaryOS be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, loss of data, or loss of professional standing.
            </p>
          </Section>

          <Section number="8" title="Termination">
            <p>
              SecretaryOS reserves the right to suspend or terminate your access to the platform at any time, with or without notice, for conduct that we believe violates these Terms of Service, misuses the platform, or is harmful to other users, third parties, or the platform itself.
            </p>
          </Section>

          <Section number="9" title="Changes to Terms">
            <p>
              We may update these Terms of Service from time to time. We will notify users of material changes by email or by a prominent notice on the platform. Your continued use of SecretaryOS after any changes constitutes your acceptance of the new terms.
            </p>
          </Section>

          <Section number="10" title="Governing Law">
            <p>
              These Terms of Service are governed by the laws of India. Any disputes arising shall be subject to the exclusive jurisdiction of the courts of India.
            </p>
          </Section>

        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gray-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <p className="text-xs text-gray-400">
            © {new Date().getFullYear()} SecretaryOS. All rights reserved.
          </p>
          <div className="flex gap-4 text-xs text-gray-400">
            <Link href="/auth" className="hover:text-ink transition-colors">Sign In</Link>
            <Link href="/" className="hover:text-ink transition-colors">Home</Link>
          </div>
        </div>

      </div>
    </div>
  )
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-bold text-ink mb-3">
        {number}. {title}
      </h2>
      <div className="text-gray-700 text-sm leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_strong]:font-semibold [&_strong]:text-ink">
        {children}
      </div>
    </div>
  )
}
