// lib/pdf-generator.ts
// Professional PDF generation using jsPDF html() method
// Handles page breaks correctly — no more text cutting through pages

export async function generatePDF(
  htmlContent: string,
  fileName: string,
  metadata: {
    companyName: string
    docType: string
    meetingDate: string
    cin: string
  }
): Promise<void> {
  await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')
  await loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js')

  const { jsPDF } = (window as any).jspdf

  // Create a temporary iframe for isolated rendering
  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:794px;height:1123px;border:none;'
  document.body.appendChild(iframe)

  const doc = iframe.contentDocument!
  doc.open()
  doc.write(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page {
    size: A4;
    margin: 0;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { width: 210mm; background: white; }

  /* Page structure */
  .page-header {
    background: #0A0F1E;
    padding: 10px 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    position: running(header);
  }
  .page-header-brand { color: #B8973A; font-size: 10px; font-weight: bold; letter-spacing: 2px; font-family: Arial, sans-serif; }
  .page-header-tag { color: #999; font-size: 8px; font-family: Arial, sans-serif; }

  .page-content {
    padding: 28px 45px 40px;
    font-family: 'Times New Roman', Times, serif;
    font-size: 11px;
    color: #1a1a1a;
    line-height: 1.65;
  }

  .page-footer {
    font-size: 8px;
    color: #999;
    font-family: Arial, sans-serif;
    border-top: 0.5px solid #ddd;
    padding: 6px 45px;
    display: flex;
    justify-content: space-between;
  }

  /* Document classes */
  .doc-title-main {
    font-size: 14px;
    font-weight: bold;
    text-align: center;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #0A0F1E;
    margin-bottom: 4px;
    page-break-inside: avoid;
    font-family: 'Times New Roman', Times, serif;
  }
  .doc-center {
    text-align: center;
    font-size: 10.5px;
    color: #333;
    margin-bottom: 3px;
    page-break-inside: avoid;
    font-family: 'Times New Roman', Times, serif;
  }
  .doc-section {
    font-size: 9.5px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    color: #B8973A;
    margin-top: 18px;
    margin-bottom: 5px;
    padding-bottom: 3px;
    border-bottom: 0.5px solid #e0e0e0;
    font-family: Arial, sans-serif;
    page-break-after: avoid;
    page-break-inside: avoid;
  }
  .doc-line {
    font-size: 11px;
    color: #2a2a2a;
    margin-bottom: 6px;
    padding-left: 10px;
    line-height: 1.7;
    font-family: 'Times New Roman', Times, serif;
    page-break-inside: avoid;
  }
  .doc-resolution {
    font-size: 11px;
    color: #1a1a1a;
    margin: 10px 0 6px 0;
    padding: 9px 12px;
    border-left: 3px solid #B8973A;
    background: #FAFAF8;
    line-height: 1.75;
    font-family: 'Times New Roman', Times, serif;
    page-break-inside: avoid;
  }
  .doc-further {
    font-size: 11px;
    color: #1a1a1a;
    margin: 5px 0 6px 0;
    padding: 7px 12px;
    border-left: 2px solid #ccc;
    background: #F8F8F6;
    line-height: 1.75;
    font-family: 'Times New Roman', Times, serif;
    page-break-inside: avoid;
  }
  .doc-sig {
    display: flex;
    justify-content: space-between;
    margin-top: 36px;
    padding-top: 16px;
    border-top: 0.5px solid #ddd;
    page-break-inside: avoid;
  }
  .doc-sig-line {
    border-top: 1px solid #333;
    width: 150px;
    margin-bottom: 3px;
    display: block;
  }
  .doc-sig div {
    font-size: 10px;
    color: #333;
    line-height: 1.6;
    font-family: 'Times New Roman', Times, serif;
  }
  strong { font-weight: bold; }

  /* Prevent orphan section headers at bottom of page */
  .doc-section + .doc-line,
  .doc-section + .doc-resolution {
    page-break-before: avoid;
  }
</style>
</head>
<body>
  <div class="page-header">
    <span class="page-header-brand">SECRETARYOS</span>
    <span class="page-header-tag">Companies Act 2013 Compliant Document</span>
  </div>

  <div class="page-content">
    ${htmlContent}
  </div>

  <div class="page-footer">
    <span>Generated by SecretaryOS &middot; ${metadata.companyName} &middot; ${metadata.cin}</span>
    <span>${metadata.meetingDate}</span>
  </div>
</body>
</html>`)
  doc.close()

  // Wait for fonts to load
  await new Promise(resolve => setTimeout(resolve, 800))

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  })

  await new Promise<void>((resolve, reject) => {
    pdf.html(iframe.contentDocument!.body, {
      callback: (doc: any) => {
        document.body.removeChild(iframe)
        doc.save(`${fileName}.pdf`)
        resolve()
      },
      x: 0,
      y: 0,
      width: 210,
      windowWidth: 794,
      autoPaging: 'text',  // KEY — this avoids cutting through text
      margin: [0, 0, 0, 0],
      html2canvas: {
        scale: 0.75,
        useCORS: true,
        backgroundColor: '#ffffff',
        logging: false,
        letterRendering: true,
      },
    })
  }).catch(err => {
    if (document.body.contains(iframe)) document.body.removeChild(iframe)
    throw err
  })
}

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) { resolve(); return }
    const s = document.createElement('script')
    s.src = src
    s.onload = () => resolve()
    s.onerror = () => reject(new Error(`Failed to load ${src}`))
    document.head.appendChild(s)
  })
}
