// Shared PDF generation utility used by generate/page.tsx and documents/[id]/page.tsx

// jsPDF's bundled Helvetica uses Latin-1 (Windows-1252) encoding.
// Any character outside that range causes the [%Ï] corruption and breaks
// word spacing for surrounding text. Replace before passing to jsPDF.
function sanitizeForPdf(text: string): string {
  return text
    .replace(/₹/g, 'Rs.')           // Rupee sign U+20B9 — not in Helvetica
    .replace(/\u2014/g, '--')        // Em dash
    .replace(/\u2013/g, '-')         // En dash
    .replace(/\u2018|\u2019/g, "'")  // Curly single quotes
    .replace(/\u201C|\u201D/g, '"')  // Curly double quotes
    .replace(/\u2026/g, '...')       // Ellipsis
    .replace(/\u00A0/g, ' ')         // Non-breaking space
    .replace(/[^\x00-\xFF]/g, '?')   // Catch-all for any remaining non-Latin-1 chars
}

const LINE_H = 5.5   // mm per line for 10pt body text
const LINE_H_SM = 4  // mm per line for 8–9pt text

export async function generateAndDownloadPDF(rawText: string, fileName: string): Promise<void> {
  const { jsPDF } = await import('jspdf')

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  function addHeader() {
    pdf.setFillColor(10, 15, 30)
    pdf.rect(0, 0, pageW, 14, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(8)
    pdf.setTextColor(184, 151, 58)
    pdf.text('SECRETARYOS', margin, 9)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(160, 160, 160)
    pdf.text('Companies Act 2013 Compliant Document', pageW - margin, 9, { align: 'right' })
  }

  function addFooter(pageNum: number, totalPages: number) {
    pdf.setFillColor(248, 248, 248)
    pdf.rect(0, pageH - 10, pageW, 10, 'F')
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(7)
    pdf.setTextColor(150, 150, 150)
    pdf.text('Generated by SecretaryOS -- AI Compliance Copilot for Company Secretaries', margin, pageH - 4)
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageW - margin, pageH - 4, { align: 'right' })
  }

  function checkPage(neededHeight: number) {
    if (y + neededHeight > pageH - 16) {
      pdf.addPage()
      addHeader()
      y = 24
    }
  }

  // Render an array of wrapped lines one by one for precise y control
  function renderLines(lines: string[], x: number, lineH: number) {
    for (const line of lines) {
      pdf.text(line, x, y)
      y += lineH
    }
  }

  addHeader()
  y = 24

  const lines = sanitizeForPdf(rawText).split('\n')

  lines.forEach(line => {
    const trimmed = line.trim()
    if (!trimmed) { y += 3; return }

    const isAllCaps = trimmed === trimmed.toUpperCase() && trimmed.length > 4 && /[A-Z]/.test(trimmed)
    const isTitle = isAllCaps && (trimmed.includes('MINUTES') || trimmed.includes('NOTICE') || trimmed.includes('RESOLUTION'))
    const isSection = isAllCaps && !isTitle && trimmed.length < 50
    const isResolution = trimmed.startsWith('RESOLVED THAT') || trimmed.startsWith('FURTHER RESOLVED')
    const isBullet = trimmed.startsWith('*') || trimmed.startsWith('-') || trimmed.startsWith('\u2022')
    const isCenter = trimmed.includes('CIN:') || trimmed.includes('Pvt Ltd') || trimmed.includes('Private Limited') || trimmed.includes('Incorporated under')

    if (isTitle) {
      checkPage(18)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(13)
      pdf.setTextColor(10, 15, 30)
      const wrapped = pdf.splitTextToSize(trimmed, contentW - 20)
      for (const wline of wrapped) {
        pdf.text(wline, pageW / 2, y, { align: 'center' })
        y += 6.5
      }
      y -= 2
      pdf.setDrawColor(184, 151, 58)
      pdf.setLineWidth(0.6)
      pdf.line(margin + 20, y, pageW - margin - 20, y)
      y += 7

    } else if (isSection) {
      checkPage(12)
      y += 3
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(8)
      pdf.setTextColor(184, 151, 58)
      pdf.text(trimmed, margin, y)
      y += LINE_H_SM - 1
      pdf.setDrawColor(220, 220, 220)
      pdf.setLineWidth(0.3)
      pdf.line(margin, y, pageW - margin, y)
      y += 4

    } else if (isResolution) {
      // Render entire resolution as bold block — no inline bold/normal split
      // which causes word-spacing corruption in some PDF viewers
      const wrapped = pdf.splitTextToSize(trimmed, contentW - 6)
      checkPage(wrapped.length * LINE_H + 4)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(10, 15, 30)
      renderLines(wrapped, margin + 4, LINE_H)
      y += 3

    } else if (isBullet) {
      const text = trimmed.replace(/^[-*\u2022]\s*/, '')
      const wrapped = pdf.splitTextToSize(text, contentW - 10)
      checkPage(wrapped.length * LINE_H + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      pdf.text('-', margin + 4, y)
      renderLines(wrapped, margin + 9, LINE_H)
      y += 2

    } else if (isCenter) {
      const wrapped = pdf.splitTextToSize(trimmed, contentW)
      checkPage(wrapped.length * LINE_H + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(80, 80, 80)
      for (const wline of wrapped) {
        pdf.text(wline, pageW / 2, y, { align: 'center' })
        y += LINE_H
      }
      y += 2

    } else if (trimmed.includes('____') || trimmed.includes('___')) {
      checkPage(14)
      y += 3
      pdf.setDrawColor(100, 100, 100)
      pdf.setLineWidth(0.4)
      pdf.line(margin + 4, y, margin + 60, y)
      pdf.line(pageW - margin - 60, y, pageW - margin - 4, y)
      y += 4
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(9)
      pdf.setTextColor(80, 80, 80)
      const label = trimmed.replace(/_+/g, '').trim()
      if (label) {
        pdf.text(label, margin + 4, y)
      }
      y += 5

    } else {
      const wrapped = pdf.splitTextToSize(trimmed, contentW - 4)
      checkPage(wrapped.length * LINE_H + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      renderLines(wrapped, margin + 4, LINE_H)
      y += 2
    }
  })

  const totalPages = pdf.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i)
    addFooter(i, totalPages)
  }

  pdf.save(fileName)
}
