// Shared PDF generation utility used by generate/page.tsx and documents/[id]/page.tsx

export async function generateAndDownloadPDF(rawText: string, fileName: string): Promise<void> {
  const { jsPDF } = await import('jspdf')

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  function addHeader() {
    pdf.setFillColor(10, 15, 30)
    pdf.rect(0, 0, pageW, 14, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(8)
    pdf.setTextColor(184, 151, 58)
    pdf.text('SECRETARYOS', margin, 9)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(160, 160, 160)
    pdf.text('Companies Act 2013 Compliant Document', pageW - margin, 9, { align: 'right' })
  }

  function addFooter(pageNum: number, totalPages: number) {
    pdf.setFillColor(248, 248, 248)
    pdf.rect(0, pageH - 10, pageW, 10, 'F')
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(7)
    pdf.setTextColor(150, 150, 150)
    pdf.text('Generated by SecretaryOS — AI Compliance Copilot for Company Secretaries', margin, pageH - 4)
    pdf.text(`Page ${pageNum} of ${totalPages}`, pageW - margin, pageH - 4, { align: 'right' })
  }

  function checkPage(neededHeight: number) {
    if (y + neededHeight > pageH - 16) {
      pdf.addPage()
      addHeader()
      y = 24
    }
  }

  addHeader()
  y = 24

  const lines = rawText.split('\n')

  lines.forEach(line => {
    const trimmed = line.trim()
    if (!trimmed) { y += 2; return }

    const isAllCaps = trimmed === trimmed.toUpperCase() && trimmed.length > 4 && /[A-Z]/.test(trimmed)
    const isTitle = isAllCaps && (trimmed.includes('MINUTES') || trimmed.includes('NOTICE') || trimmed.includes('RESOLUTION'))
    const isSection = isAllCaps && !isTitle && trimmed.length < 50
    const isResolution = trimmed.startsWith('RESOLVED THAT') || trimmed.startsWith('FURTHER RESOLVED')
    const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-')
    const isCenter = trimmed.includes('CIN:') || trimmed.includes('Pvt Ltd') || trimmed.includes('Private Limited') || trimmed.includes('Incorporated under')

    if (isTitle) {
      checkPage(16)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(13)
      pdf.setTextColor(10, 15, 30)
      pdf.text(trimmed, pageW / 2, y, { align: 'center' })
      y += 3
      pdf.setDrawColor(184, 151, 58)
      pdf.setLineWidth(0.6)
      pdf.line(margin + 20, y, pageW - margin - 20, y)
      y += 8
    } else if (isSection) {
      checkPage(12)
      y += 2
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(8)
      pdf.setTextColor(184, 151, 58)
      pdf.text(trimmed, margin, y)
      y += 1.5
      pdf.setDrawColor(230, 230, 230)
      pdf.setLineWidth(0.3)
      pdf.line(margin, y, pageW - margin, y)
      y += 5
    } else if (isResolution) {
      const keyword = trimmed.startsWith('FURTHER RESOLVED THAT') ? 'FURTHER RESOLVED THAT' : 'RESOLVED THAT'
      const rest = trimmed.substring(keyword.length).trim()
      const full = keyword + (rest ? ' ' + rest : '')
      const wrapped = pdf.splitTextToSize(full, contentW - 6)
      checkPage(wrapped.length * 5 + 4)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(10, 15, 30)
      pdf.text(keyword, margin + 4, y)
      if (rest) {
        pdf.setFont('helvetica', 'normal')
        const restWrapped = pdf.splitTextToSize(rest, contentW - 6 - pdf.getTextWidth(keyword) - 3)
        pdf.text(restWrapped[0] || '', margin + 4 + pdf.getTextWidth(keyword) + 2, y)
        if (restWrapped.length > 1) {
          y += 5
          pdf.text(restWrapped.slice(1), margin + 4, y)
          y += (restWrapped.length - 1) * 5
        }
      }
      y += 7
    } else if (isBullet) {
      const text = trimmed.substring(1).trim()
      const wrapped = pdf.splitTextToSize(text, contentW - 10)
      checkPage(wrapped.length * 5 + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      pdf.text('•', margin + 4, y)
      pdf.text(wrapped, margin + 9, y)
      y += wrapped.length * 5 + 2
    } else if (isCenter) {
      const wrapped = pdf.splitTextToSize(trimmed, contentW)
      checkPage(wrapped.length * 5 + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(80, 80, 80)
      pdf.text(wrapped, pageW / 2, y, { align: 'center' })
      y += wrapped.length * 5 + 2
    } else if (trimmed.includes('____')) {
      checkPage(14)
      y += 2
      pdf.setDrawColor(100, 100, 100)
      pdf.setLineWidth(0.4)
      if (trimmed.toLowerCase().includes('secretary') || trimmed.toLowerCase().includes('chairman')) {
        pdf.line(margin + 4, y, margin + 60, y)
        pdf.line(pageW - margin - 60, y, pageW - margin - 4, y)
      }
      y += 4
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(9)
      pdf.setTextColor(80, 80, 80)
      pdf.text(trimmed.replace(/_+/g, '').trim(), margin + 4, y)
      y += 6
    } else {
      const wrapped = pdf.splitTextToSize(trimmed, contentW - 4)
      checkPage(wrapped.length * 5 + 2)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      pdf.text(wrapped, margin + 4, y)
      y += wrapped.length * 5 + 2
    }
  })

  const totalPages = pdf.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i)
    addFooter(i, totalPages)
  }

  pdf.save(fileName)
}
