'use client'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import { createClient } from '@/lib/supabase'

export default function DocumentPage() {
  const params = useParams()
  const router = useRouter()
  const supabase = createClient()
  const [doc, setDoc] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    async function fetchDoc() {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) { router.push('/auth'); return }

      const { data } = await supabase
        .from('documents')
        .select('*, clients(id, company_name, cin, registered_office)')
        .eq('id', params.id as string)
        .single()

      if (!data) { router.push('/documents'); return }
      setDoc(data)
      setLoading(false)
    }
    fetchDoc()
  }, [])

  async function downloadPDF() {
    if (!doc) return
    setDownloading(true)

    // Strip HTML to get plain text
    const tmp = document.createElement('div')
    tmp.innerHTML = doc.content
    const rawText = tmp.innerText || tmp.textContent || ''

    // Load jsPDF
    await new Promise<void>((resolve, reject) => {
      if ((window as any).jspdf) { resolve(); return }
      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
      script.onload = () => resolve()
      script.onerror = reject
      document.head.appendChild(script)
    })

    const { jsPDF } = (window as any).jspdf
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = pdf.internal.pageSize.getHeight()
    const margin = 20
    const contentW = pageW - margin * 2
    let y = margin

    function addHeader() {
      pdf.setFillColor(10, 15, 30)
      pdf.rect(0, 0, pageW, 14, 'F')
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(8)
      pdf.setTextColor(184, 151, 58)
      pdf.text('SECRETARYOS', margin, 9)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(160, 160, 160)
      pdf.text('Companies Act 2013 Compliant Document', pageW - margin, 9, { align: 'right' })
    }

    function addFooter(pageNum: number, totalPages: number) {
      pdf.setFillColor(248, 248, 248)
      pdf.rect(0, pageH - 10, pageW, 10, 'F')
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(7)
      pdf.setTextColor(150, 150, 150)
      pdf.text('Generated by SecretaryOS — AI Compliance Copilot for Company Secretaries', margin, pageH - 4)
      pdf.text(`Page ${pageNum} of ${totalPages}`, pageW - margin, pageH - 4, { align: 'right' })
    }

    function checkPage(neededHeight: number) {
      if (y + neededHeight > pageH - 16) {
        pdf.addPage()
        addHeader()
        y = 24
      }
    }

    addHeader()
    y = 24

    const lines = rawText.split('\n')
    lines.forEach((line: string) => {
      const trimmed = line.trim()
      if (!trimmed) { y += 2; return }

      const isAllCaps = trimmed === trimmed.toUpperCase() && trimmed.length > 4 && /[A-Z]/.test(trimmed)
      const isTitle = isAllCaps && (trimmed.includes('MINUTES') || trimmed.includes('NOTICE') || trimmed.includes('RESOLUTION'))
      const isSection = isAllCaps && !isTitle && trimmed.length < 50
      const isResolution = trimmed.startsWith('RESOLVED THAT') || trimmed.startsWith('FURTHER RESOLVED')
      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-')
      const isCenter = trimmed.includes('CIN:') || trimmed.includes('Pvt Ltd') || trimmed.includes('Private Limited') || trimmed.includes('Incorporated under')

      if (isTitle) {
        checkPage(16)
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(13)
        pdf.setTextColor(10, 15, 30)
        pdf.text(trimmed, pageW / 2, y, { align: 'center' })
        y += 3
        pdf.setDrawColor(184, 151, 58)
        pdf.setLineWidth(0.6)
        pdf.line(margin + 20, y, pageW - margin - 20, y)
        y += 8
      } else if (isSection) {
        checkPage(12)
        y += 2
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(8)
        pdf.setTextColor(184, 151, 58)
        pdf.text(trimmed, margin, y)
        y += 1.5
        pdf.setDrawColor(230, 230, 230)
        pdf.setLineWidth(0.3)
        pdf.line(margin, y, pageW - margin, y)
        y += 5
      } else if (isResolution) {
        checkPage(10)
        const keyword = trimmed.startsWith('FURTHER RESOLVED THAT') ? 'FURTHER RESOLVED THAT' : 'RESOLVED THAT'
        const rest = trimmed.substring(keyword.length).trim()
        checkPage(10)
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(10)
        pdf.setTextColor(10, 15, 30)
        pdf.text(keyword, margin + 4, y)
        if (rest) {
          pdf.setFont('helvetica', 'normal')
          const restWrapped = pdf.splitTextToSize(rest, contentW - 6 - pdf.getTextWidth(keyword) - 3)
          pdf.text(restWrapped[0] || '', margin + 4 + pdf.getTextWidth(keyword) + 2, y)
          if (restWrapped.length > 1) {
            y += 5
            pdf.text(restWrapped.slice(1), margin + 4, y)
            y += (restWrapped.length - 1) * 5
          }
        }
        y += 7
      } else if (isBullet) {
        const text = trimmed.substring(1).trim()
        const wrapped = pdf.splitTextToSize(text, contentW - 10)
        checkPage(wrapped.length * 5 + 2)
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(10)
        pdf.setTextColor(60, 60, 60)
        pdf.text('•', margin + 4, y)
        pdf.text(wrapped, margin + 9, y)
        y += wrapped.length * 5 + 2
      } else if (isCenter) {
        const wrapped = pdf.splitTextToSize(trimmed, contentW)
        checkPage(wrapped.length * 5 + 2)
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(10)
        pdf.setTextColor(80, 80, 80)
        pdf.text(wrapped, pageW / 2, y, { align: 'center' })
        y += wrapped.length * 5 + 2
      } else {
        const wrapped = pdf.splitTextToSize(trimmed, contentW - 4)
        checkPage(wrapped.length * 5 + 2)
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(10)
        pdf.setTextColor(60, 60, 60)
        pdf.text(wrapped, margin + 4, y)
        y += wrapped.length * 5 + 2
      }
    })

    const totalPages = pdf.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      addFooter(i, totalPages)
    }

    const fileName = `${doc.title?.replace(/[^a-z0-9]/gi, '_') || 'document'}.pdf`
    pdf.save(fileName)
    setDownloading(false)
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#FDFCF9]">
        <Navbar />
        <main className="pt-24 px-6 max-w-5xl mx-auto">
          <div className="flex items-center gap-3 text-slate-400 text-sm">
            <div className="w-4 h-4 border-2 border-slate-300 border-t-slate-600 rounded-full animate-spin"></div>
            Loading document...
          </div>
        </main>
      </div>
    )
  }

  const meta = doc.metadata as any

  return (
    <div className="min-h-screen bg-[#FDFCF9]">
      <Navbar />
      <main className="pt-24 pb-16 px-6 max-w-5xl mx-auto">

        <div className="flex items-center gap-2 text-sm text-slate-400 mb-6">
          <Link href="/documents" className="hover:text-ink transition-colors">Documents</Link>
          <span>/</span>
          <span className="text-ink truncate max-w-xs">{doc.title}</span>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* DOCUMENT */}
          <div className="lg:col-span-2">
            <div className="bg-white border border-slate-100 rounded-2xl overflow-hidden">
              <div className="bg-ink px-6 py-4 flex items-center justify-between">
                <div>
                  <p className="text-xs text-slate-400">Generated document</p>
                  <p className="text-sm text-white font-medium mt-0.5">{doc.title}</p>
                </div>
                <span className="text-xs px-3 py-1 bg-green-500/20 text-green-400 rounded-full border border-green-500/20">
                  ✓ Companies Act compliant
                </span>
              </div>
              <div className="p-8 doc-preview leading-relaxed" dangerouslySetInnerHTML={{ __html: doc.content }} />
            </div>
          </div>

          {/* SIDEBAR */}
          <div className="space-y-4">
            {/* ACTIONS */}
            <div className="bg-white border border-slate-100 rounded-2xl p-5">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-4">Actions</p>
              <div className="space-y-2">
                <button
                  onClick={downloadPDF}
                  disabled={downloading}
                  className="w-full py-2.5 bg-ink text-white text-sm font-medium rounded-xl hover:bg-slate-800 transition-colors disabled:opacity-60 flex items-center justify-center gap-2"
                >
                  {downloading ? (
                    <><span className="w-3 h-3 border border-white/30 border-t-white rounded-full animate-spin inline-block"></span>Preparing PDF...</>
                  ) : '↓ Download PDF'}
                </button>
                <Link
                  href={`/generate?client=${doc.clients?.id}`}
                  className="block w-full py-2.5 border border-slate-200 text-ink text-sm font-medium rounded-xl hover:bg-slate-50 transition-colors text-center"
                >
                  ✦ Generate another
                </Link>
              </div>
            </div>

            {/* METADATA */}
            <div className="bg-white border border-slate-100 rounded-2xl p-5">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-4">Document details</p>
              <div className="space-y-3">
                {[
                  { label: 'Company', val: doc.clients?.company_name },
                  { label: 'CIN', val: doc.clients?.cin },
                  { label: 'Document type', val: doc.type?.replace('_', ' ') },
                  { label: 'Meeting date', val: meta?.meeting_date ? new Date(meta.meeting_date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : '—' },
                  { label: 'Meeting venue', val: meta?.meeting_venue || '—' },
                  { label: 'Generated on', val: new Date(doc.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) },
                ].map(item => (
                  <div key={item.label}>
                    <p className="text-xs text-slate-400">{item.label}</p>
                    <p className="text-sm text-ink font-medium capitalize">{item.val || '—'}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* COMPLIANCE */}
            <div className="bg-green-50 border border-green-200 rounded-2xl p-5">
              <p className="text-xs font-semibold uppercase tracking-wider text-green-700 mb-3">Compliance checklist</p>
              <div className="space-y-2">
                {[
                  'Section 173 — Meeting convened',
                  'Section 174 — Quorum confirmed',
                  'SS-1 — Secretarial Standards',
                  'Section 118(1) — Signing timeline',
                  'DIN numbers verified',
                  'Statutory language compliant',
                ].map(item => (
                  <div key={item} className="flex items-center gap-2 text-xs text-green-700">
                    <span className="text-green-500 flex-shrink-0">✓</span>
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
