import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const maxDuration = 60

export async function POST(req: NextRequest) {
  try {
    const { html, fileName, companyName, cin, meetingDate } = await req.json()

    if (!html) {
      return NextResponse.json({ error: 'No HTML content provided' }, { status: 400 })
    }

    const fullHtml = buildDocumentHtml(html, { companyName, cin, meetingDate })
    const pdfBuffer = await generatePDF(fullHtml)

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fileName || 'document'}.pdf"`,
        'Content-Length': String(pdfBuffer.length),
      },
    })

  } catch (error: any) {
    console.error('PDF generation error:', error)
    return NextResponse.json(
      { error: error.message || 'PDF generation failed' },
      { status: 500 }
    )
  }
}

async function generatePDF(html: string): Promise<Buffer> {
  let browser: any = null

  try {
    const chromium = require('@sparticuz/chromium')
    const puppeteer = require('puppeteer-core')

    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: true,
    })

    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })

    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
      displayHeaderFooter: false,
    })

    return Buffer.from(pdf)

  } finally {
    if (browser) await browser.close()
  }
}

function buildDocumentHtml(content: string, meta: { companyName?: string; cin?: string; meetingDate?: string }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page { size: A4; margin: 0; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { width: 210mm; font-family: 'Times New Roman', Times, serif; font-size: 11pt; color: #1a1a1a; background: white; }

  .doc-header { background: #0A0F1E; padding: 10px 40px; display: flex; justify-content: space-between; align-items: center; position: fixed; top: 0; left: 0; right: 0; }
  .doc-header-brand { color: #B8973A; font-size: 10pt; font-weight: bold; letter-spacing: 2px; font-family: Arial, sans-serif; }
  .doc-header-tag { color: #888; font-size: 8pt; font-family: Arial, sans-serif; }

  .doc-footer { position: fixed; bottom: 0; left: 0; right: 0; background: #F8F8F6; border-top: 0.5px solid #ddd; padding: 5px 40px; display: flex; justify-content: space-between; font-size: 7.5pt; color: #999; font-family: Arial, sans-serif; }

  .doc-body { margin-top: 46px; margin-bottom: 32px; padding: 28px 42px 20px; }

  .doc-title-main { font-size: 13.5pt; font-weight: bold; text-align: center; text-transform: uppercase; letter-spacing: 0.5px; color: #0A0F1E; margin-bottom: 5px; line-height: 1.3; }
  .doc-center { text-align: center; font-size: 10pt; color: #333; margin-bottom: 3px; line-height: 1.5; }
  .doc-section { font-size: 9pt; font-weight: bold; text-transform: uppercase; letter-spacing: 1.5px; color: #B8973A; margin-top: 18pt; margin-bottom: 5pt; padding-bottom: 3pt; border-bottom: 0.5px solid #e0e0e0; font-family: Arial, sans-serif; page-break-after: avoid; }
  .doc-line { font-size: 10.5pt; color: #2a2a2a; margin-bottom: 6pt; padding-left: 10px; line-height: 1.7; page-break-inside: avoid; orphans: 3; widows: 3; }
  .doc-resolution { font-size: 10.5pt; color: #1a1a1a; margin: 10pt 0 6pt 0; padding: 9pt 12px; border-left: 3px solid #B8973A; background: #FAFAF8; line-height: 1.75; page-break-inside: avoid; }
  .doc-further { font-size: 10.5pt; color: #1a1a1a; margin: 5pt 0 6pt 0; padding: 7pt 12px; border-left: 2px solid #ccc; background: #F8F8F6; line-height: 1.75; page-break-inside: avoid; }
  .doc-sig { display: flex; justify-content: space-between; margin-top: 36pt; padding-top: 16pt; border-top: 0.5px solid #ddd; page-break-inside: avoid; }
  .doc-sig-line { border-top: 1px solid #333; width: 150px; margin-bottom: 4px; display: block; }
  .doc-sig div { font-size: 9.5pt; color: #333; line-height: 1.7; }
  strong { font-weight: bold; }
</style>
</head>
<body>
  <div class="doc-header">
    <span class="doc-header-brand">SECRETARYOS</span>
    <span class="doc-header-tag">Companies Act 2013 Compliant Document</span>
  </div>
  <div class="doc-footer">
    <span>Generated by SecretaryOS &middot; ${meta.companyName || ''} &middot; ${meta.cin || ''}</span>
    <span>${meta.meetingDate || ''}</span>
  </div>
  <div class="doc-body">${content}</div>
</body>
</html>`
}
