import { NextRequest, NextResponse } from 'next/server'
import { writeFileSync, readFileSync, existsSync, mkdirSync, copyFileSync } from 'fs'
import { execSync } from 'child_process'
import { join, resolve } from 'path'
import { tmpdir } from 'os'
import { randomBytes } from 'crypto'
import { htmlToTypst } from '@/lib/typst/html-to-typst'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

export const runtime = 'nodejs'
export const maxDuration = 60

// Find typst binary — works both locally and on Vercel
// outputFileTracingIncludes copies ./bin/typst into the serverless bundle
function getTypstBinary(): string {
  const candidates = [
    // Vercel: binary bundled relative to project root
    resolve(process.cwd(), 'bin', 'typst'),
    // Vercel: Next.js traces files relative to the route file
    join(__dirname, '..', '..', '..', '..', 'bin', 'typst'),
    join(__dirname, '..', '..', '..', 'bin', 'typst'),
    join(__dirname, '..', '..', 'bin', 'typst'),
    // System install
    '/usr/local/bin/typst',
  ]

  for (const p of candidates) {
    if (existsSync(p)) {
      console.log('Found typst at:', p)
      return p
    }
  }

  // Last resort — try PATH
  try {
    execSync('typst --version', { stdio: 'pipe' })
    return 'typst'
  } catch {}

  return ''
}

function getTemplateDir(): string {
  const candidates = [
    resolve(process.cwd(), 'lib', 'typst'),
    join(__dirname, '..', '..', '..', '..', 'lib', 'typst'),
    join(__dirname, '..', '..', '..', 'lib', 'typst'),
  ]
  for (const p of candidates) {
    if (existsSync(p)) return p
  }
  return resolve(process.cwd(), 'lib', 'typst')
}

export async function POST(req: NextRequest) {
  const jobId = randomBytes(8).toString('hex')
  const workDir = join(tmpdir(), `sos-${jobId}`)

  try {
    const {
      html, fileName, companyName, cin, meetingDate,
      place, chairmanName, chairmanDin, csName, csMembership,
      signatoryName, signatoryDesignation, signatoryDin,
      customTemplate,
    } = await req.json()

    if (!html) {
      return NextResponse.json({ error: 'No HTML content provided' }, { status: 400 })
    }

    const cookieStore = cookies()
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          get: (n: string) => cookieStore.get(n)?.value,
          set() {},
          remove() {},
        },
      }
    )
    const { data: { user } } = await supabase.auth.getUser()
    let isDemo = false
    if (user) {
      const { data: sub } = await supabase.from('subscriptions').select('plan').eq('user_id', user.id).single()
      isDemo = sub?.plan === 'demo'
    }

    const typstBin = getTypstBinary()
    if (!typstBin) {
      console.error('Typst binary not found. Searched:', [
        resolve(process.cwd(), 'bin', 'typst'),
        '/usr/local/bin/typst',
      ])
      return NextResponse.json(
        { error: 'PDF engine not available — please contact support' },
        { status: 500 }
      )
    }

    mkdirSync(workDir, { recursive: true })

    // Write template
    const templateDest = join(workDir, 'template.typ')
    if (customTemplate) {
      writeFileSync(templateDest, customTemplate, 'utf-8')
    } else {
      const templateSrc = join(getTemplateDir(), 'template.typ')
      if (existsSync(templateSrc)) {
        copyFileSync(templateSrc, templateDest)
      } else {
        writeFileSync(templateDest, getDefaultTemplate(isDemo), 'utf-8')
      }
    }

    // Append PDF disclaimer footer to the HTML before conversion
    const generatedAt = new Date().toLocaleString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true, timeZone: 'Asia/Kolkata',
    })
    const disclaimerHtml = `<div class="doc-disclaimer-footer">DRAFT FOR PROFESSIONAL REVIEW AND VERIFICATION — Generated by SecretaryOS on ${generatedAt} IST — This is an AI-generated document. It is a draft only and must be thoroughly reviewed by the Company Secretary before filing with ROC. You are solely responsible for all content and accuracy. SecretaryOS makes no warranties and disclaims all liability.</div>`
    const htmlWithFooter = html + disclaimerHtml

    // Convert HTML → Typst
    const typstContent = htmlToTypst(htmlWithFooter, {
      company_name: companyName || '',
      cin: cin || '',
      meeting_date: meetingDate || '',
      place: place || 'India',
      chairman_name: chairmanName || '',
      chairman_din: chairmanDin || '',
      cs_name: csName || '',
      cs_membership: csMembership || '',
      signatory_name: signatoryName || '',
      signatory_designation: signatoryDesignation || '',
      signatory_din: signatoryDin || '',
    })

    const typstFile = join(workDir, 'document.typ')
    const outputFile = join(workDir, 'document.pdf')
    writeFileSync(typstFile, typstContent, 'utf-8')

    // Compile
    try {
      execSync(`"${typstBin}" compile "${typstFile}" "${outputFile}"`, {
        timeout: 30000,
        stdio: 'pipe',
        cwd: workDir,
      })
    } catch (err: any) {
      const stderr = err.stderr?.toString() || ''
      const stdout = err.stdout?.toString() || ''
      console.error('=== TYPST ERROR ===')
      console.error('stderr:', stderr)
      console.error('stdout:', stdout)
      console.error('typst bin:', typstBin)
      console.error('workDir:', workDir)
      console.error('=== TYPST SOURCE ===')
      console.error(typstContent)
      cleanup(workDir)
      return NextResponse.json(
        { error: 'Typst error: ' + (stderr || stdout || err.message).slice(0, 500) },
        { status: 500 }
      )
    }

    if (!existsSync(outputFile)) {
      cleanup(workDir)
      return NextResponse.json({ error: 'PDF output not generated' }, { status: 500 })
    }

    const pdfBuffer = readFileSync(outputFile)
    cleanup(workDir)

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fileName || 'document'}.pdf"`,
        'Content-Length': String(pdfBuffer.length),
      },
    })

  } catch (error: any) {
    cleanup(workDir)
    console.error('PDF generation error:', error)
    return NextResponse.json({ error: error.message || 'PDF generation failed' }, { status: 500 })
  }
}

function cleanup(dir: string) {
  try { execSync(`rm -rf "${dir}"`, { stdio: 'pipe' }) } catch {}
}

function getDefaultTemplate(isDemo: boolean = false): string {
  const demoHeader = isDemo
    ? `context { if counter(page).get().first() > 1 [ #grid(columns: (1fr, 1fr), [#set text(size: 8pt, weight: "bold", fill: rgb("#B8973A"), tracking: 2pt); SECRETARYOS], align(right)[#set text(size: 8pt, fill: rgb("#888888")); Companies Act 2013 Compliant]) #line(length: 100%, stroke: 0.5pt + rgb("#0A0F1E")) ] }`
    : `context { if counter(page).get().first() > 1 [ #line(length: 100%, stroke: 0.5pt + rgb("#dddddd")) ] }`
  return `
#let doc(company_name: "", cin: "", meeting_date: "", body) = {
  set page(
    paper: "a4",
    margin: (top: 2.5cm, bottom: 2.5cm, left: 2.54cm, right: 2.54cm),
    header: ${demoHeader},
    footer: none
  )
  set text(font: ("Cambria", "Liberation Serif", "Times New Roman", "serif"), size: 11pt, lang: "en")
  set par(justify: true, leading: 0.8em)
  body
}
#let doc-title(content) = { set align(center); set text(size: 13pt, weight: "bold"); upper(content); v(4pt) }
#let doc-meeting-title(content) = { set align(left); set par(justify: true); set text(size: 11pt, weight: "bold"); upper(content); v(8pt) }
#let doc-center(content) = { set align(center); set text(size: 11pt); content; v(2pt) }
#let doc-divider() = { v(4pt); line(length: 100%, stroke: 0.5pt + black); v(8pt) }
#let doc-section(content) = { v(8pt); set text(size: 11pt, weight: "bold", fill: black, tracking: 0.5pt); upper(content); v(4pt) }
#let doc-line(content) = { pad(left: 0pt)[#set text(size: 11pt); #content]; v(3pt) }
#let doc-resolution(content) = { v(6pt); block(width: 100%)[#set text(size: 11pt); #content]; v(4pt) }
#let doc-further(content) = { v(3pt); block(width: 100%)[#set text(size: 11pt); #content]; v(4pt) }
#let doc-sig(chairman_name: "", chairman_din: "", cs_name: "", cs_membership: "", date: "", place: "") = {
  v(24pt); line(length: 100%, stroke: 0.5pt + rgb("#cccccc")); v(12pt)
  grid(columns: (1fr, 1fr), gutter: 20pt,
    [#set text(size: 10pt); *CHAIRMAN OF THE MEETING* #v(24pt) #line(length: 80%, stroke: 0.5pt + black) #v(3pt) Name: #chairman_name \\ DIN: #chairman_din \\ Date: #date \\ Place: #place],
    [#set text(size: 10pt); *COMPANY SECRETARY* #v(24pt) #line(length: 80%, stroke: 0.5pt + black) #v(3pt) Name: #cs_name \\ Membership No.: #cs_membership \\ Date: #date \\ Place: #place]
  )
}
#let doc_notice_sig(name: "", designation: "", din: "", date: "", place: "") = {
  v(24pt); line(length: 100%, stroke: 0.5pt + rgb("#cccccc")); v(12pt)
  [#set text(size: 10pt); #v(24pt) #line(length: 40%, stroke: 0.5pt + black) #v(3pt) *#name* \\ #designation \\ DIN: #din \\ Place: __________]
}
#let doc-disclaimer-footer(content) = {
  v(24pt)
  line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
  v(6pt)
  set text(size: 8pt, fill: rgb("#888888"))
  set par(justify: false)
  content
  v(4pt)
}
`.trim()
}